### ISSUE TITLE
회원 가입 페이지 업데이트

### ISSUE THREAD

**Issue by heeedol** [wafflestudio/gatgu-client#269]
## TODO:
- [ ] keyboard avoiding view 추가 
- [ ] 체크박스 등 디자인 수정
- [ ] 이메일 인증 작동되게 + 이메일 다시보내기
- [ ] 주소 선택 기능
