### ISSUE TITLE
모집 글 관련 오류 해결

### ISSUE THREAD

**Issue by heeedol** [wafflestudio/gatgu-client#331]
## TODO
- [x] 글 삭제 후 홈 화면 리로딩
- [x] 글 작성 화면의 `TouchableHighlight` 제거하기
- [x] 글 작성 화면의 사진 클릭시 대표 섬네일로 지정
- [x] 쉬머 뜨기 전 이전 컨텐츠 보이는 에러
- [x] 글 수정 후 리로드
